#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    testConsole = bld.program(features = [ 'cxx' ],
                              uselib = [ 'BOOST' ],
                              use = [ 'Rsd' ],
                              target = 'testConsole',
                              source = [ 'TestConsole.cpp' ])
    
    test1 = bld.program(features = [ 'cxx' ],
                        uselib = [ 'BOOST' ],
                        use = [ 'Rsd' ],
                        target = 'test1',
                        source = [ 'Test1.cpp' ],
                        install_path = None)
    
    test2 = bld.program(features = [ 'cxx' ],
                        uselib = [ 'BOOST' ],
                        use = [ 'Rsd' ],
                        target = 'test2',
                        source = [ 'Test2.cpp' ],
                        install_path = None)
