#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    testConsole = bld.program(features = [ 'cxx' ],
                              uselib = [ 'BOOST' ],
                              use = [ 'Rsd' ],
                              target = 'testConsole',
                              source = [ 'TestConsole.cpp' ])
    
    testConsole = bld.program(features = [ 'cxx' ],
                              uselib = [ 'BOOST' ],
                              use = [ 'Rsd' ],
                              target = 'test1',
                              source = [ 'Test1.cpp' ])
    
