#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    # Build lemon itself
    lemon = bld.program(features = [ 'c' ],
                        target = 'lemon',
                        source = [ 'lemon.c' ])

    # Copy parser source template to build dir
    lempar = bld(name = 'lempar',
                 rule = 'cp ${SRC[0].abspath()} ${TGT}',
                 source = bld.path.make_node('lempar.c.in'),
                 target = 'lempar.c')

