#define kToken_ASSIGN                          1
#define kToken_SEMICOLON                       2
#define kToken_INCLUDE                         3
#define kToken_STRING                          4
#define kToken_IDENTIFIER                      5
#define kToken_DOT                             6
#define kToken_AT                              7
#define kToken_INTEGER                         8
#define kToken_FLOAT                           9
#define kToken_BOOLEAN                        10
#define kToken_LEFTCURLYBRACKET               11
#define kToken_RIGHTCURLYBRACKET              12
#define kToken_COLON                          13
#define kToken_LEFTSQUAREBRACKET              14
#define kToken_RIGHTSQUAREBRACKET             15
#define kToken_COMMA                          16
#define kToken_LEFTPAREN                      17
#define kToken_RIGHTPAREN                     18
