#define kReferenceToken_ASSIGN                          1
#define kReferenceToken_SEMICOLON                       2
#define kReferenceToken_INCLUDE                         3
#define kReferenceToken_STRING                          4
#define kReferenceToken_IDENTIFIER                      5
#define kReferenceToken_DOT                             6
#define kReferenceToken_AT                              7
#define kReferenceToken_INTEGER                         8
#define kReferenceToken_FLOAT                           9
#define kReferenceToken_BOOLEAN                        10
#define kReferenceToken_LEFTCURLYBRACKET               11
#define kReferenceToken_RIGHTCURLYBRACKET              12
#define kReferenceToken_COLON                          13
#define kReferenceToken_LEFTSQUAREBRACKET              14
#define kReferenceToken_RIGHTSQUAREBRACKET             15
#define kReferenceToken_COMMA                          16
#define kReferenceToken_LEFTPAREN                      17
#define kReferenceToken_RIGHTPAREN                     18
